### ISSUE TITLE
$.fn.velocity is undefined

### ISSUE THREAD

**Issue by Noitidart** [jondot/react-flight#16]
Hi there,

Thanks for this project it is very cool.

I included jQuery, however when try to go to next frame with either play or interactive, I get

> $.fn.velocity is undefined.

`$` and `jQuery` are definitely available in the global of the bundle (not global window scope though)

The only way for me to fix this was by not relying on webpack and instead adding in:

> <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.slim.min.js"></script>

**Comment by jondot** [comment]
Hi, 
For this to work you'd need to tell webpack to put jquery as global, this link is from the README https://webpack.github.io/docs/library-and-externals.html.

Currently we depend on Velocityjs (which turns out to be the best overall animation library for Javascript, that still has great performance on Mobile), so that's the tradeoff in favor of better performance. The integration layer is requiring jQuery (or any jQuery-like library like Zepto) to be available globally.

Please feel free to reopen this issue if that doesn't work for you.
