### ISSUE TITLE
Error Command "start" not found 

### ISSUE THREAD

**Issue by ummahusla** [jondot/react-flight#6]
Thanks for fixing in #2 but it still seems to be broken as I cannot compile it. Same issue exists both for `yarn && yarn start` and `npm i && npm start`.

Should be the line in readme replaced to ` yarn && yarn build`?

___

📝 **Log** when `yarn && yarn start`

```
edvins.antonovs@NEMO MINGW64 /d/repos
$ git clone https://github.com/jondot/react-flight
Cloning into 'react-flight'...
remote: Counting objects: 171, done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 171 (delta 62), reused 158 (delta 49), pack-reused 0
Receiving objects: 100% (171/171), 1.60 MiB | 1.25 MiB/s, done.
Resolving deltas: 100% (62/62), done.

edvins.antonovs@NEMO MINGW64 /d/repos
$ cd react-flight

edvins.antonovs@NEMO MINGW64 /d/repos/react-flight (master)
$ yarn && yarn start
yarn install v0.23.2
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.0.15: The platform "win32" is incompatible with this module.
info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it
 from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 20.88s.
yarn start v0.23.2
error Command "start" not found.
```

**Comment by jondot** [comment]
So, there are two projects actually in this repo. One is react-flight itself, which you can build and hack on if you want to add things to it. 

Otherwise you can use it as-is, and this is where you go to the `examples` folder and try out the example there. The example should have a `start` command.

I'll review the README and see how to make this more obvious, thanks!

**Comment by ummahusla** [comment]
@jondot Right I see. Yeah, `readme` seems to be missing a bit of the information.
